

// write a function that found if the world is palindrome or not
function palindrome(word) {
  const orderWord = word.split("");
  const reversedWord = orderWord.reverse();
  const revesedString = reversedWord.join("").toLowerCase();
  console.log(revesedString);

  if (word.toLowerCase() === revesedString.toLowerCase()) {
    return true;
  }
  return false;
}

console.log(palindrome("radar"));


// Generated by Qodo Gen

describe('palindrome', () => {

    // Test with single character word like 'a'
    it('should return true when given a single character word', () => {
      const word = 'a';
      const result = palindrome(word);
      expect(result).toBe(true);
    });
});
